using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Enums
{
    public enum CHAR_TYPE { WARRIOR1, WARRIOR2, WARRIOR3, ARCHER1, ARCHER2, ARCHER3, ASSASSIN1, ASSASSIN2, ASSASSIN3, MAGICIAN1, MAGICIAN2, MAGICIAN3, DEFENDER1, DEFENDER2, DEFENDER3 }
    public enum PORTRAIT_TYPE { NORMAL, SUMMON, SUPER, BUTTON, MINI }

    public enum SCENE_TYPE { MAIN_MENU, LOBBY, STAGE }
}